$(document).ready(function(){
    $('.des').click(function(){
        $('.design-dec').toggle(100)
    })
});
$(document).ready(function(){
    $('.dev').click(function(){
        $('#dev-dev').toggle(100)
    })
});